### ISSUE TITLE
ERROR 1193 (HY000) at line 1: Unknown system variable 'tx_isolation' with a MySQL DB version 8.1

### ISSUE THREAD

**Issue by BRUTEF0RCE** [sameersbn/docker-redmine#550]
I was having issues with the docker-redmine:5.1.2 container with a MySQL version 8.1 database. For some reason, the docker-redmine container kept stopping on error :

```
ERROR 1193 (HY000) at line 1: Unknown system variable 'tx_isolation'
```

Here is the log of the docker-redmine container I was obtaining : 

```
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
ERROR 1193 (HY000) at line 1: Unknown system variable 'tx_isolation'
Checking transaction isolation level... 
```

After a bit of code reading, I think I found the culprit in the asset/runtime/functions file. Since "set -e" option is declared at the beginning of the script, your 2nd and 3rd 'if' statements will never be reached after the first mysql call that will return an error if this call is made to a MySQL version 8.1 database. I think you might want to unset the "set -e" option with "set +e" before this section of code, and set it back after, as shown below.

```bash
redmine_check_mysql_database_tx_isolation() {
  # Print warning if transaction isolation level in mysql is not READ-COMMITTED, which is required to avoid race conditions
  # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
  if [[ ${DB_ADAPTER} == mysql2 ]]; then
    set +e
    echo -n "Checking transaction isolation level... "
    mysql_cmd="mysql \
          --host "${DB_HOST}" --port "${DB_PORT}" \
          --user "${DB_USER}" --default-character-set "${DB_ENCODING}" \
          --skip-column-names \
          --silent "
    isolation_lvl=$( MYSQL_PWD="${DB_PASS}" $mysql_cmd \
          --execute="SELECT @@GLOBAL.tx_isolation;" )

    if [[ $? -ne 0 ]]; then
      # try the new name of the variable, mysql 8+
      isolation_lvl=$( MYSQL_PWD="${DB_PASS}" $mysql_cmd \
            --execute="SELECT @@GLOBAL.transaction_isolation;" )

      if [[ $? -ne 0 ]]; then
        echo
        echo "ERROR: Failed to check transaction isolation level" >&2
        return 1
      fi
    fi

    echo "$isolation_lvl"

    if [[ ${isolation_lvl} != "READ-COMMITTED" ]]
    then
      echo "WARNING: transaction isolation level is not READ-COMMITTED" >&2
      echo "WARNING: Read more about this issue at:" >&2
      echo "https://www.redmine.org/projects/redmine/wiki/MySQL_configuration" >&2
    fi
    set -e
  fi
}
```

With this fix, I now have a proper instance of the docker redmine container in place. Here is the new log : 

```
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
ERROR 1193 (HY000) at line 1: Unknown system variable 'tx_isolation'
Checking transaction isolation level... READ-COMMITTED
Configuring redmine::memcached...
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::email_delivery...
Configuring redmine::backups...
Configuring redmine::rmagic::font...
Configuring redmine::avatar::url...
Configuring nginx...
Configuring nginx::redmine...
Installing plugins...
Installing themes...
2024-03-27 22:32:56,504 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2024-03-27 22:32:56,504 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2024-03-27 22:32:56,504 INFO Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2024-03-27 22:32:56,504 INFO Set uid to user 0 succeeded
2024-03-27 22:32:56,506 INFO RPC interface 'supervisor' initialized
2024-03-27 22:32:56,506 INFO supervisord started with pid 1
2024-03-27 22:32:57,509 INFO spawned: 'unicorn' with pid 310
2024-03-27 22:32:57,510 INFO spawned: 'cron' with pid 311
2024-03-27 22:32:57,511 INFO spawned: 'nginx' with pid 312
2024-03-27 22:32:58,818 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-27 22:32:58,818 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-27 22:32:58,818 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

```

**Comment by jcormier** [comment]
I pushed a fix to the master branch. Can you confirm it fixes your issue and I'll release the tags.

**Comment by BRUTEF0RCE** [comment]
Here is the new log with your changes. It still shows the error but keep going : 

```
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
ERROR 1193 (HY000) at line 1: Unknown system variable 'tx_isolation'
Checking transaction isolation level... READ-COMMITTED
Configuring redmine::memcached...
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::email_delivery...
Configuring redmine::backups...
Configuring redmine::rmagic::font...
Configuring redmine::avatar::url...
Configuring nginx...
Configuring nginx::redmine...
Installing plugins...
Installing themes...
2024-03-28 15:09:13,675 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2024-03-28 15:09:13,675 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2024-03-28 15:09:13,675 INFO Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2024-03-28 15:09:13,675 INFO Set uid to user 0 succeeded
2024-03-28 15:09:13,677 INFO RPC interface 'supervisor' initialized
2024-03-28 15:09:13,677 INFO supervisord started with pid 1
2024-03-28 15:09:14,679 INFO spawned: 'unicorn' with pid 310
2024-03-28 15:09:14,680 INFO spawned: 'cron' with pid 311
2024-03-28 15:09:14,681 INFO spawned: 'nginx' with pid 312
2024-03-28 15:09:15,987 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-28 15:09:15,987 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-28 15:09:15,987 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by jcormier** [comment]
Thanks do you have a docker compose config for configuring the mysql:8.1.0 image?

**Comment by BRUTEF0RCE** [comment]
Good job!  Thank you for this! :)
